/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
 * The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.
 *
 * OpenAPI spec version: v1.26.15-post
 */
import useSwr from "swr";
import type { Arguments, Key, SWRConfiguration } from "swr";
import useSWRMutation from "swr/mutation";
import type { SWRMutationConfiguration } from "swr/mutation";

import { fetcher } from "../client";
import type {
  BadRequestResponse,
  ForbiddenResponse,
  Identifier,
  InternalServerErrorResponse,
  NotFoundResponse,
  TrailActionRunCancelOKResponse,
  TrailCreateBody,
  TrailCreateOKResponse,
  TrailGetOKResponse,
  TrailListOKResponse,
  TrailRunGetOKResponse,
  TrailRunListOKResponse,
  TrailRunNowOKResponse,
  TrailSchedulePreviewBody,
  TrailSchedulePreviewOKResponse,
  TrailUpdateBody,
  TrailUpdateOKResponse,
  UnauthorisedResponse,
} from "../openapi-schema";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getTrailListUrl = () => {
  return `/trails`;
};

/**
 * Return all Trail definitions that the requesting account can manage.
 * Each item includes its trigger, action bindings, lifecycle state, and
 * latest occurrence times. Archived Trails remain in the result.
 * @summary List Trails
 */
export const trailList = async (
  options?: Parameters<typeof fetcher>[1],
): Promise<TrailListOKResponse> => {
  return fetcher<TrailListOKResponse>(getTrailListUrl(), {
    ...options,
    method: "GET",
  });
};

export const getTrailListKey = () => [`/trails`] as const;

export type TrailListQueryResult = NonNullable<
  Awaited<ReturnType<typeof trailList>>
>;

/**
 * @summary List Trails
 */
export const useTrailList = <
  TError =
    UnauthorisedResponse | ForbiddenResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof trailList>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof fetcher>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getTrailListKey() : null));
  const swrFn = () => trailList(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
export const getTrailCreateUrl = () => {
  return `/trails`;
};

/**
 * Create a Trail with one trigger and one or more action bindings. The
 * server records the requesting account as the creator and validates the
 * trigger, actions, and lifecycle state. An active Trail receives its next
 * occurrence when the trigger has a future occurrence.
 * @summary Create a Trail
 */
export const trailCreate = async (
  trailCreateBody: TrailCreateBody,
  options?: Parameters<typeof fetcher>[1],
): Promise<TrailCreateOKResponse> => {
  return fetcher<TrailCreateOKResponse>(getTrailCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(trailCreateBody),
  });
};

export const getTrailCreateMutationFetcher = (
  options?: SecondParameter<typeof fetcher>,
) => {
  return (_: Key, { arg }: { arg: TrailCreateBody }) => {
    return trailCreate(arg, options);
  };
};
export const getTrailCreateMutationKey = () => [`/trails`] as const;

export type TrailCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof trailCreate>>
>;

/**
 * @summary Create a Trail
 */
export const useTrailCreate = <
  TError =
    | BadRequestResponse
    | UnauthorisedResponse
    | ForbiddenResponse
    | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof trailCreate>>,
    TError,
    Key,
    TrailCreateBody,
    Awaited<ReturnType<typeof trailCreate>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof fetcher>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getTrailCreateMutationKey();
  const swrFn = getTrailCreateMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export const getTrailSchedulePreviewUrl = () => {
  return `/trails/schedule/preview`;
};

/**
 * Validate a schedule and return its next five occurrences after the
 * supplied time. The operation does not create or update a Trail. The
 * calculation skips local times that do not exist and emits an ambiguous
 * local time once.
 * @summary Preview the next five schedule occurrences
 */
export const trailSchedulePreview = async (
  trailSchedulePreviewBody: TrailSchedulePreviewBody,
  options?: Parameters<typeof fetcher>[1],
): Promise<TrailSchedulePreviewOKResponse> => {
  return fetcher<TrailSchedulePreviewOKResponse>(getTrailSchedulePreviewUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(trailSchedulePreviewBody),
  });
};

export const getTrailSchedulePreviewMutationFetcher = (
  options?: SecondParameter<typeof fetcher>,
) => {
  return (_: Key, { arg }: { arg: TrailSchedulePreviewBody }) => {
    return trailSchedulePreview(arg, options);
  };
};
export const getTrailSchedulePreviewMutationKey = () =>
  [`/trails/schedule/preview`] as const;

export type TrailSchedulePreviewMutationResult = NonNullable<
  Awaited<ReturnType<typeof trailSchedulePreview>>
>;

/**
 * @summary Preview the next five schedule occurrences
 */
export const useTrailSchedulePreview = <
  TError =
    | BadRequestResponse
    | UnauthorisedResponse
    | ForbiddenResponse
    | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof trailSchedulePreview>>,
    TError,
    Key,
    TrailSchedulePreviewBody,
    Awaited<ReturnType<typeof trailSchedulePreview>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof fetcher>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getTrailSchedulePreviewMutationKey();
  const swrFn = getTrailSchedulePreviewMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export const getTrailGetUrl = (trailId: Identifier) => {
  return `/trails/${trailId}`;
};

/**
 * Return one Trail definition. The response includes the current trigger,
 * active action bindings, lifecycle state, and occurrence times. The
 * operation does not return run history.
 * @summary Get a Trail
 */
export const trailGet = async (
  trailId: Identifier,
  options?: Parameters<typeof fetcher>[1],
): Promise<TrailGetOKResponse> => {
  return fetcher<TrailGetOKResponse>(getTrailGetUrl(trailId), {
    ...options,
    method: "GET",
  });
};

export const getTrailGetKey = (trailId: Identifier) =>
  [`/trails/${trailId}`] as const;

export type TrailGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof trailGet>>
>;

/**
 * @summary Get a Trail
 */
export const useTrailGet = <
  TError =
    | UnauthorisedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  trailId: Identifier,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof trailGet>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled =
    swrOptions?.enabled !== false && trailId !== null && trailId !== undefined;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getTrailGetKey(trailId) : null));
  const swrFn = () => trailGet(trailId, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
export const getTrailUpdateUrl = (trailId: Identifier) => {
  return `/trails/${trailId}`;
};

/**
 * Replace the mutable Trail definition. The server validates the trigger
 * and action bindings before it saves the update. The creator is immutable.
 * A status change can pause, resume, or archive the Trail. Archive keeps
 * existing run history and does not cancel action runs that already
 * started.
 * @summary Update a Trail, including pause, resume, finish, or archive
 */
export const trailUpdate = async (
  trailId: Identifier,
  trailUpdateBody: TrailUpdateBody,
  options?: Parameters<typeof fetcher>[1],
): Promise<TrailUpdateOKResponse> => {
  return fetcher<TrailUpdateOKResponse>(getTrailUpdateUrl(trailId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(trailUpdateBody),
  });
};

export const getTrailUpdateMutationFetcher = (
  trailId: Identifier,
  options?: SecondParameter<typeof fetcher>,
) => {
  return (_: Key, { arg }: { arg: TrailUpdateBody }) => {
    return trailUpdate(trailId, arg, options);
  };
};
export const getTrailUpdateMutationKey = (trailId: Identifier) =>
  [`/trails/${trailId}`] as const;

export type TrailUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof trailUpdate>>
>;

/**
 * @summary Update a Trail, including pause, resume, finish, or archive
 */
export const useTrailUpdate = <
  TError =
    | BadRequestResponse
    | UnauthorisedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  trailId: Identifier,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof trailUpdate>>,
      TError,
      Key,
      TrailUpdateBody,
      Awaited<ReturnType<typeof trailUpdate>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getTrailUpdateMutationKey(trailId);
  const swrFn = getTrailUpdateMutationFetcher(trailId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export const getTrailRunListUrl = (trailId: Identifier) => {
  return `/trails/${trailId}/runs`;
};

/**
 * Return the 100 most recent runs for one Trail. Each run contains an
 * immutable trigger snapshot and the independent result of every action
 * binding. The result includes scheduled, manual, and skipped runs.
 * @summary List Trail run history
 */
export const trailRunList = async (
  trailId: Identifier,
  options?: Parameters<typeof fetcher>[1],
): Promise<TrailRunListOKResponse> => {
  return fetcher<TrailRunListOKResponse>(getTrailRunListUrl(trailId), {
    ...options,
    method: "GET",
  });
};

export const getTrailRunListKey = (trailId: Identifier) =>
  [`/trails/${trailId}/runs`] as const;

export type TrailRunListQueryResult = NonNullable<
  Awaited<ReturnType<typeof trailRunList>>
>;

/**
 * @summary List Trail run history
 */
export const useTrailRunList = <
  TError =
    | UnauthorisedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  trailId: Identifier,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof trailRunList>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled =
    swrOptions?.enabled !== false && trailId !== null && trailId !== undefined;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getTrailRunListKey(trailId) : null));
  const swrFn = () => trailRunList(trailId, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
export const getTrailRunNowUrl = (trailId: Identifier) => {
  return `/trails/${trailId}/runs`;
};

/**
 * Create a new manual run and its action runs immediately. The operation
 * does not change the next scheduled occurrence. An archived Trail cannot
 * start a manual run.
 * @summary Create a manual Trail occurrence without moving its schedule
 */
export const trailRunNow = async (
  trailId: Identifier,
  options?: Parameters<typeof fetcher>[1],
): Promise<TrailRunNowOKResponse> => {
  return fetcher<TrailRunNowOKResponse>(getTrailRunNowUrl(trailId), {
    ...options,
    method: "POST",
  });
};

export const getTrailRunNowMutationFetcher = (
  trailId: Identifier,
  options?: SecondParameter<typeof fetcher>,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return trailRunNow(trailId, options);
  };
};
export const getTrailRunNowMutationKey = (trailId: Identifier) =>
  [`/trails/${trailId}/runs`] as const;

export type TrailRunNowMutationResult = NonNullable<
  Awaited<ReturnType<typeof trailRunNow>>
>;

/**
 * @summary Create a manual Trail occurrence without moving its schedule
 */
export const useTrailRunNow = <
  TError =
    | BadRequestResponse
    | UnauthorisedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  trailId: Identifier,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof trailRunNow>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof trailRunNow>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getTrailRunNowMutationKey(trailId);
  const swrFn = getTrailRunNowMutationFetcher(trailId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export const getTrailRunGetUrl = (trailId: Identifier, runId: Identifier) => {
  return `/trails/${trailId}/runs/${runId}`;
};

/**
 * Return one Trail run and its action runs. The response contains the
 * immutable trigger snapshot, aggregate status, action configuration
 * snapshots, outputs, errors, and linked Robot resources.
 * @summary Get a Trail run and its independent action results
 */
export const trailRunGet = async (
  trailId: Identifier,
  runId: Identifier,
  options?: Parameters<typeof fetcher>[1],
): Promise<TrailRunGetOKResponse> => {
  return fetcher<TrailRunGetOKResponse>(getTrailRunGetUrl(trailId, runId), {
    ...options,
    method: "GET",
  });
};

export const getTrailRunGetKey = (trailId: Identifier, runId: Identifier) =>
  [`/trails/${trailId}/runs/${runId}`] as const;

export type TrailRunGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof trailRunGet>>
>;

/**
 * @summary Get a Trail run and its independent action results
 */
export const useTrailRunGet = <
  TError =
    | UnauthorisedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  trailId: Identifier,
  runId: Identifier,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof trailRunGet>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled =
    swrOptions?.enabled !== false &&
    trailId !== null &&
    trailId !== undefined &&
    runId !== null &&
    runId !== undefined;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getTrailRunGetKey(trailId, runId) : null));
  const swrFn = () => trailRunGet(trailId, runId, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
export const getTrailActionRunCancelUrl = (
  trailId: Identifier,
  runId: Identifier,
  actionRunId: Identifier,
) => {
  return `/trails/${trailId}/runs/${runId}/actions/${actionRunId}/cancellation`;
};

/**
 * Request cancellation for one queued or running Robot action. A queued
 * action is cancelled before it starts. A running action forwards the
 * cancellation request to the Robot session coordinator. Other action
 * runs in the same Trail run continue independently.
 * @summary Cancel an active Robot action
 */
export const trailActionRunCancel = async (
  trailId: Identifier,
  runId: Identifier,
  actionRunId: Identifier,
  options?: Parameters<typeof fetcher>[1],
): Promise<TrailActionRunCancelOKResponse> => {
  return fetcher<TrailActionRunCancelOKResponse>(
    getTrailActionRunCancelUrl(trailId, runId, actionRunId),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getTrailActionRunCancelMutationFetcher = (
  trailId: Identifier,
  runId: Identifier,
  actionRunId: Identifier,
  options?: SecondParameter<typeof fetcher>,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return trailActionRunCancel(trailId, runId, actionRunId, options);
  };
};
export const getTrailActionRunCancelMutationKey = (
  trailId: Identifier,
  runId: Identifier,
  actionRunId: Identifier,
) =>
  [
    `/trails/${trailId}/runs/${runId}/actions/${actionRunId}/cancellation`,
  ] as const;

export type TrailActionRunCancelMutationResult = NonNullable<
  Awaited<ReturnType<typeof trailActionRunCancel>>
>;

/**
 * @summary Cancel an active Robot action
 */
export const useTrailActionRunCancel = <
  TError =
    | BadRequestResponse
    | UnauthorisedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  trailId: Identifier,
  runId: Identifier,
  actionRunId: Identifier,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof trailActionRunCancel>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof trailActionRunCancel>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof fetcher>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ??
    getTrailActionRunCancelMutationKey(trailId, runId, actionRunId);
  const swrFn = getTrailActionRunCancelMutationFetcher(
    trailId,
    runId,
    actionRunId,
    requestOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
