run:
  tests: false

  go: "1.18"

  issues-exit-code: 0
  skip-files:
    - "graphql/.+\\.resolvers\\.go"

severity:
  default-severity: warn

linters:
  fast: true
  enable:
    - gci
    - wrapcheck
  presets:
    - bugs
    - unused
    - format

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/Southclaws/storyden)
  wrapcheck:
    ignoreSigs:
      - fault.New(
      - fault.Newf(
      - fault.Wrap(
