version: "3"

services:
  postgres:
    image: postgres:18-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-default}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default}

  redis:
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
