version: 3

dotenv:
  - .env

vars:
  VERSION:
    sh: git describe --always --tags
  DOCKER_IMAGE_TAG: "storyden:{{.VERSION}}"

tasks:
  default:
    deps: [backend]
    cmds:
      - ./backend.exe
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - app/**/*.go

  production:
    cmds:
      - ./backend.exe

  backend:
    cmds:
      - go build -o backend.exe -ldflags="-X 'github.com/Southclaws/storyden/internal/config.Version={{.VERSION}}'" ./cmd/backend
  backend:test:
    cmds:
      - go test ./...

  # -
  # Docker
  # -

  backend:image:build:
    cmds:
      - docker build -t {{.DOCKER_IMAGE_TAG}} .

  backend:image:run:
    cmds:
      - docker run {{.DOCKER_IMAGE_TAG}}

  # -
  # Code generation
  # -

  generate:
    deps: [generate:db, generate:openapi, generate:graphql]

  generate:db:
    cmds: [go generate ./internal/ent]

  generate:openapi:
    deps: [generate:openapi:backend, generate:openapi:frontend]
  generate:openapi:backend:
    cmds: [go generate ./internal/openapi]
  generate:openapi:frontend:
    dir: web
    cmds: [yarn openapi]

  generate:graphql:
    cmds: [go generate ./app/transports/graphql]

  # -
  # Database
  # -

  seed:
    cmds:
      - go run ./cmd/seed

  db:ui:
    cmds:
      - atlas schema inspect -d {{.DATABASE_URL}} -w
