// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/email"
	"github.com/rs/xid"
)

// EmailCreate is the builder for creating a Email entity.
type EmailCreate struct {
	config
	mutation *EmailMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ec *EmailCreate) SetCreatedAt(t time.Time) *EmailCreate {
	ec.mutation.SetCreatedAt(t)
	return ec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ec *EmailCreate) SetNillableCreatedAt(t *time.Time) *EmailCreate {
	if t != nil {
		ec.SetCreatedAt(*t)
	}
	return ec
}

// SetAccountID sets the "account_id" field.
func (ec *EmailCreate) SetAccountID(x xid.ID) *EmailCreate {
	ec.mutation.SetAccountID(x)
	return ec
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (ec *EmailCreate) SetNillableAccountID(x *xid.ID) *EmailCreate {
	if x != nil {
		ec.SetAccountID(*x)
	}
	return ec
}

// SetEmailAddress sets the "email_address" field.
func (ec *EmailCreate) SetEmailAddress(s string) *EmailCreate {
	ec.mutation.SetEmailAddress(s)
	return ec
}

// SetVerified sets the "verified" field.
func (ec *EmailCreate) SetVerified(b bool) *EmailCreate {
	ec.mutation.SetVerified(b)
	return ec
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (ec *EmailCreate) SetNillableVerified(b *bool) *EmailCreate {
	if b != nil {
		ec.SetVerified(*b)
	}
	return ec
}

// SetIsAuth sets the "is_auth" field.
func (ec *EmailCreate) SetIsAuth(b bool) *EmailCreate {
	ec.mutation.SetIsAuth(b)
	return ec
}

// SetNillableIsAuth sets the "is_auth" field if the given value is not nil.
func (ec *EmailCreate) SetNillableIsAuth(b *bool) *EmailCreate {
	if b != nil {
		ec.SetIsAuth(*b)
	}
	return ec
}

// SetID sets the "id" field.
func (ec *EmailCreate) SetID(x xid.ID) *EmailCreate {
	ec.mutation.SetID(x)
	return ec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ec *EmailCreate) SetNillableID(x *xid.ID) *EmailCreate {
	if x != nil {
		ec.SetID(*x)
	}
	return ec
}

// SetAccount sets the "account" edge to the Account entity.
func (ec *EmailCreate) SetAccount(a *Account) *EmailCreate {
	return ec.SetAccountID(a.ID)
}

// Mutation returns the EmailMutation object of the builder.
func (ec *EmailCreate) Mutation() *EmailMutation {
	return ec.mutation
}

// Save creates the Email in the database.
func (ec *EmailCreate) Save(ctx context.Context) (*Email, error) {
	ec.defaults()
	return withHooks(ctx, ec.sqlSave, ec.mutation, ec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EmailCreate) SaveX(ctx context.Context) *Email {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EmailCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EmailCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *EmailCreate) defaults() {
	if _, ok := ec.mutation.CreatedAt(); !ok {
		v := email.DefaultCreatedAt()
		ec.mutation.SetCreatedAt(v)
	}
	if _, ok := ec.mutation.Verified(); !ok {
		v := email.DefaultVerified
		ec.mutation.SetVerified(v)
	}
	if _, ok := ec.mutation.IsAuth(); !ok {
		v := email.DefaultIsAuth
		ec.mutation.SetIsAuth(v)
	}
	if _, ok := ec.mutation.ID(); !ok {
		v := email.DefaultID()
		ec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *EmailCreate) check() error {
	if _, ok := ec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Email.created_at"`)}
	}
	if _, ok := ec.mutation.EmailAddress(); !ok {
		return &ValidationError{Name: "email_address", err: errors.New(`ent: missing required field "Email.email_address"`)}
	}
	if v, ok := ec.mutation.EmailAddress(); ok {
		if err := email.EmailAddressValidator(v); err != nil {
			return &ValidationError{Name: "email_address", err: fmt.Errorf(`ent: validator failed for field "Email.email_address": %w`, err)}
		}
	}
	if _, ok := ec.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`ent: missing required field "Email.verified"`)}
	}
	if _, ok := ec.mutation.IsAuth(); !ok {
		return &ValidationError{Name: "is_auth", err: errors.New(`ent: missing required field "Email.is_auth"`)}
	}
	if v, ok := ec.mutation.ID(); ok {
		if err := email.IDValidator(v.String()); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Email.id": %w`, err)}
		}
	}
	return nil
}

func (ec *EmailCreate) sqlSave(ctx context.Context) (*Email, error) {
	if err := ec.check(); err != nil {
		return nil, err
	}
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ec.mutation.id = &_node.ID
	ec.mutation.done = true
	return _node, nil
}

func (ec *EmailCreate) createSpec() (*Email, *sqlgraph.CreateSpec) {
	var (
		_node = &Email{config: ec.config}
		_spec = sqlgraph.NewCreateSpec(email.Table, sqlgraph.NewFieldSpec(email.FieldID, field.TypeString))
	)
	_spec.OnConflict = ec.conflict
	if id, ok := ec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ec.mutation.CreatedAt(); ok {
		_spec.SetField(email.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ec.mutation.EmailAddress(); ok {
		_spec.SetField(email.FieldEmailAddress, field.TypeString, value)
		_node.EmailAddress = value
	}
	if value, ok := ec.mutation.Verified(); ok {
		_spec.SetField(email.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := ec.mutation.IsAuth(); ok {
		_spec.SetField(email.FieldIsAuth, field.TypeBool, value)
		_node.IsAuth = value
	}
	if nodes := ec.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   email.AccountTable,
			Columns: []string{email.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Email.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ec *EmailCreate) OnConflict(opts ...sql.ConflictOption) *EmailUpsertOne {
	ec.conflict = opts
	return &EmailUpsertOne{
		create: ec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Email.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ec *EmailCreate) OnConflictColumns(columns ...string) *EmailUpsertOne {
	ec.conflict = append(ec.conflict, sql.ConflictColumns(columns...))
	return &EmailUpsertOne{
		create: ec,
	}
}

type (
	// EmailUpsertOne is the builder for "upsert"-ing
	//  one Email node.
	EmailUpsertOne struct {
		create *EmailCreate
	}

	// EmailUpsert is the "OnConflict" setter.
	EmailUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *EmailUpsert) SetAccountID(v xid.ID) *EmailUpsert {
	u.Set(email.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *EmailUpsert) UpdateAccountID() *EmailUpsert {
	u.SetExcluded(email.FieldAccountID)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *EmailUpsert) ClearAccountID() *EmailUpsert {
	u.SetNull(email.FieldAccountID)
	return u
}

// SetVerified sets the "verified" field.
func (u *EmailUpsert) SetVerified(v bool) *EmailUpsert {
	u.Set(email.FieldVerified, v)
	return u
}

// UpdateVerified sets the "verified" field to the value that was provided on create.
func (u *EmailUpsert) UpdateVerified() *EmailUpsert {
	u.SetExcluded(email.FieldVerified)
	return u
}

// SetIsAuth sets the "is_auth" field.
func (u *EmailUpsert) SetIsAuth(v bool) *EmailUpsert {
	u.Set(email.FieldIsAuth, v)
	return u
}

// UpdateIsAuth sets the "is_auth" field to the value that was provided on create.
func (u *EmailUpsert) UpdateIsAuth() *EmailUpsert {
	u.SetExcluded(email.FieldIsAuth)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Email.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(email.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EmailUpsertOne) UpdateNewValues() *EmailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(email.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(email.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.EmailAddress(); exists {
			s.SetIgnore(email.FieldEmailAddress)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Email.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EmailUpsertOne) Ignore() *EmailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailUpsertOne) DoNothing() *EmailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailCreate.OnConflict
// documentation for more info.
func (u *EmailUpsertOne) Update(set func(*EmailUpsert)) *EmailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *EmailUpsertOne) SetAccountID(v xid.ID) *EmailUpsertOne {
	return u.Update(func(s *EmailUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *EmailUpsertOne) UpdateAccountID() *EmailUpsertOne {
	return u.Update(func(s *EmailUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *EmailUpsertOne) ClearAccountID() *EmailUpsertOne {
	return u.Update(func(s *EmailUpsert) {
		s.ClearAccountID()
	})
}

// SetVerified sets the "verified" field.
func (u *EmailUpsertOne) SetVerified(v bool) *EmailUpsertOne {
	return u.Update(func(s *EmailUpsert) {
		s.SetVerified(v)
	})
}

// UpdateVerified sets the "verified" field to the value that was provided on create.
func (u *EmailUpsertOne) UpdateVerified() *EmailUpsertOne {
	return u.Update(func(s *EmailUpsert) {
		s.UpdateVerified()
	})
}

// SetIsAuth sets the "is_auth" field.
func (u *EmailUpsertOne) SetIsAuth(v bool) *EmailUpsertOne {
	return u.Update(func(s *EmailUpsert) {
		s.SetIsAuth(v)
	})
}

// UpdateIsAuth sets the "is_auth" field to the value that was provided on create.
func (u *EmailUpsertOne) UpdateIsAuth() *EmailUpsertOne {
	return u.Update(func(s *EmailUpsert) {
		s.UpdateIsAuth()
	})
}

// Exec executes the query.
func (u *EmailUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EmailUpsertOne) ID(ctx context.Context) (id xid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: EmailUpsertOne.ID is not supported by MySQL driver. Use EmailUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EmailUpsertOne) IDX(ctx context.Context) xid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EmailCreateBulk is the builder for creating many Email entities in bulk.
type EmailCreateBulk struct {
	config
	err      error
	builders []*EmailCreate
	conflict []sql.ConflictOption
}

// Save creates the Email entities in the database.
func (ecb *EmailCreateBulk) Save(ctx context.Context) ([]*Email, error) {
	if ecb.err != nil {
		return nil, ecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Email, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ecb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EmailCreateBulk) SaveX(ctx context.Context) []*Email {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EmailCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EmailCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Email.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ecb *EmailCreateBulk) OnConflict(opts ...sql.ConflictOption) *EmailUpsertBulk {
	ecb.conflict = opts
	return &EmailUpsertBulk{
		create: ecb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Email.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ecb *EmailCreateBulk) OnConflictColumns(columns ...string) *EmailUpsertBulk {
	ecb.conflict = append(ecb.conflict, sql.ConflictColumns(columns...))
	return &EmailUpsertBulk{
		create: ecb,
	}
}

// EmailUpsertBulk is the builder for "upsert"-ing
// a bulk of Email nodes.
type EmailUpsertBulk struct {
	create *EmailCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Email.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(email.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EmailUpsertBulk) UpdateNewValues() *EmailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(email.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(email.FieldCreatedAt)
			}
			if _, exists := b.mutation.EmailAddress(); exists {
				s.SetIgnore(email.FieldEmailAddress)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Email.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EmailUpsertBulk) Ignore() *EmailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailUpsertBulk) DoNothing() *EmailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailCreateBulk.OnConflict
// documentation for more info.
func (u *EmailUpsertBulk) Update(set func(*EmailUpsert)) *EmailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *EmailUpsertBulk) SetAccountID(v xid.ID) *EmailUpsertBulk {
	return u.Update(func(s *EmailUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *EmailUpsertBulk) UpdateAccountID() *EmailUpsertBulk {
	return u.Update(func(s *EmailUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *EmailUpsertBulk) ClearAccountID() *EmailUpsertBulk {
	return u.Update(func(s *EmailUpsert) {
		s.ClearAccountID()
	})
}

// SetVerified sets the "verified" field.
func (u *EmailUpsertBulk) SetVerified(v bool) *EmailUpsertBulk {
	return u.Update(func(s *EmailUpsert) {
		s.SetVerified(v)
	})
}

// UpdateVerified sets the "verified" field to the value that was provided on create.
func (u *EmailUpsertBulk) UpdateVerified() *EmailUpsertBulk {
	return u.Update(func(s *EmailUpsert) {
		s.UpdateVerified()
	})
}

// SetIsAuth sets the "is_auth" field.
func (u *EmailUpsertBulk) SetIsAuth(v bool) *EmailUpsertBulk {
	return u.Update(func(s *EmailUpsert) {
		s.SetIsAuth(v)
	})
}

// UpdateIsAuth sets the "is_auth" field to the value that was provided on create.
func (u *EmailUpsertBulk) UpdateIsAuth() *EmailUpsertBulk {
	return u.Update(func(s *EmailUpsert) {
		s.UpdateIsAuth()
	})
}

// Exec executes the query.
func (u *EmailUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EmailCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
