// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/predicate"
	"github.com/Southclaws/storyden/internal/ent/robotmemory"
	"github.com/rs/xid"
)

// RobotMemoryUpdate is the builder for updating RobotMemory entities.
type RobotMemoryUpdate struct {
	config
	hooks     []Hook
	mutation  *RobotMemoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RobotMemoryUpdate builder.
func (_u *RobotMemoryUpdate) Where(ps ...predicate.RobotMemory) *RobotMemoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RobotMemoryUpdate) SetUpdatedAt(v time.Time) *RobotMemoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRobotRef sets the "robot_ref" field.
func (_u *RobotMemoryUpdate) SetRobotRef(v string) *RobotMemoryUpdate {
	_u.mutation.SetRobotRef(v)
	return _u
}

// SetNillableRobotRef sets the "robot_ref" field if the given value is not nil.
func (_u *RobotMemoryUpdate) SetNillableRobotRef(v *string) *RobotMemoryUpdate {
	if v != nil {
		_u.SetRobotRef(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *RobotMemoryUpdate) SetParentID(v xid.ID) *RobotMemoryUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *RobotMemoryUpdate) SetNillableParentID(v *xid.ID) *RobotMemoryUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *RobotMemoryUpdate) ClearParentID() *RobotMemoryUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetContent sets the "content" field.
func (_u *RobotMemoryUpdate) SetContent(v string) *RobotMemoryUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *RobotMemoryUpdate) SetNillableContent(v *string) *RobotMemoryUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *RobotMemoryUpdate) SetSubject(v string) *RobotMemoryUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *RobotMemoryUpdate) SetNillableSubject(v *string) *RobotMemoryUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// ClearSubject clears the value of the "subject" field.
func (_u *RobotMemoryUpdate) ClearSubject() *RobotMemoryUpdate {
	_u.mutation.ClearSubject()
	return _u
}

// SetPredicate sets the "predicate" field.
func (_u *RobotMemoryUpdate) SetPredicate(v string) *RobotMemoryUpdate {
	_u.mutation.SetPredicate(v)
	return _u
}

// SetNillablePredicate sets the "predicate" field if the given value is not nil.
func (_u *RobotMemoryUpdate) SetNillablePredicate(v *string) *RobotMemoryUpdate {
	if v != nil {
		_u.SetPredicate(*v)
	}
	return _u
}

// ClearPredicate clears the value of the "predicate" field.
func (_u *RobotMemoryUpdate) ClearPredicate() *RobotMemoryUpdate {
	_u.mutation.ClearPredicate()
	return _u
}

// SetObject sets the "object" field.
func (_u *RobotMemoryUpdate) SetObject(v string) *RobotMemoryUpdate {
	_u.mutation.SetObject(v)
	return _u
}

// SetNillableObject sets the "object" field if the given value is not nil.
func (_u *RobotMemoryUpdate) SetNillableObject(v *string) *RobotMemoryUpdate {
	if v != nil {
		_u.SetObject(*v)
	}
	return _u
}

// ClearObject clears the value of the "object" field.
func (_u *RobotMemoryUpdate) ClearObject() *RobotMemoryUpdate {
	_u.mutation.ClearObject()
	return _u
}

// SetState sets the "state" field.
func (_u *RobotMemoryUpdate) SetState(v robotmemory.State) *RobotMemoryUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *RobotMemoryUpdate) SetNillableState(v *robotmemory.State) *RobotMemoryUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetLastAccessedAt sets the "last_accessed_at" field.
func (_u *RobotMemoryUpdate) SetLastAccessedAt(v time.Time) *RobotMemoryUpdate {
	_u.mutation.SetLastAccessedAt(v)
	return _u
}

// SetNillableLastAccessedAt sets the "last_accessed_at" field if the given value is not nil.
func (_u *RobotMemoryUpdate) SetNillableLastAccessedAt(v *time.Time) *RobotMemoryUpdate {
	if v != nil {
		_u.SetLastAccessedAt(*v)
	}
	return _u
}

// SetAccessCount sets the "access_count" field.
func (_u *RobotMemoryUpdate) SetAccessCount(v uint64) *RobotMemoryUpdate {
	_u.mutation.ResetAccessCount()
	_u.mutation.SetAccessCount(v)
	return _u
}

// SetNillableAccessCount sets the "access_count" field if the given value is not nil.
func (_u *RobotMemoryUpdate) SetNillableAccessCount(v *uint64) *RobotMemoryUpdate {
	if v != nil {
		_u.SetAccessCount(*v)
	}
	return _u
}

// AddAccessCount adds value to the "access_count" field.
func (_u *RobotMemoryUpdate) AddAccessCount(v int64) *RobotMemoryUpdate {
	_u.mutation.AddAccessCount(v)
	return _u
}

// SetParent sets the "parent" edge to the RobotMemory entity.
func (_u *RobotMemoryUpdate) SetParent(v *RobotMemory) *RobotMemoryUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the RobotMemory entity by IDs.
func (_u *RobotMemoryUpdate) AddChildIDs(ids ...xid.ID) *RobotMemoryUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the RobotMemory entity.
func (_u *RobotMemoryUpdate) AddChildren(v ...*RobotMemory) *RobotMemoryUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the RobotMemoryMutation object of the builder.
func (_u *RobotMemoryUpdate) Mutation() *RobotMemoryMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the RobotMemory entity.
func (_u *RobotMemoryUpdate) ClearParent() *RobotMemoryUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the RobotMemory entity.
func (_u *RobotMemoryUpdate) ClearChildren() *RobotMemoryUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to RobotMemory entities by IDs.
func (_u *RobotMemoryUpdate) RemoveChildIDs(ids ...xid.ID) *RobotMemoryUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to RobotMemory entities.
func (_u *RobotMemoryUpdate) RemoveChildren(v ...*RobotMemory) *RobotMemoryUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RobotMemoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RobotMemoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RobotMemoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RobotMemoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RobotMemoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := robotmemory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RobotMemoryUpdate) check() error {
	if v, ok := _u.mutation.RobotRef(); ok {
		if err := robotmemory.RobotRefValidator(v); err != nil {
			return &ValidationError{Name: "robot_ref", err: fmt.Errorf(`ent: validator failed for field "RobotMemory.robot_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := robotmemory.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "RobotMemory.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := robotmemory.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "RobotMemory.state": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RobotMemoryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RobotMemoryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RobotMemoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(robotmemory.Table, robotmemory.Columns, sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(robotmemory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RobotRef(); ok {
		_spec.SetField(robotmemory.FieldRobotRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(robotmemory.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(robotmemory.FieldSubject, field.TypeString, value)
	}
	if _u.mutation.SubjectCleared() {
		_spec.ClearField(robotmemory.FieldSubject, field.TypeString)
	}
	if value, ok := _u.mutation.Predicate(); ok {
		_spec.SetField(robotmemory.FieldPredicate, field.TypeString, value)
	}
	if _u.mutation.PredicateCleared() {
		_spec.ClearField(robotmemory.FieldPredicate, field.TypeString)
	}
	if value, ok := _u.mutation.Object(); ok {
		_spec.SetField(robotmemory.FieldObject, field.TypeString, value)
	}
	if _u.mutation.ObjectCleared() {
		_spec.ClearField(robotmemory.FieldObject, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(robotmemory.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastAccessedAt(); ok {
		_spec.SetField(robotmemory.FieldLastAccessedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccessCount(); ok {
		_spec.SetField(robotmemory.FieldAccessCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAccessCount(); ok {
		_spec.AddField(robotmemory.FieldAccessCount, field.TypeUint64, value)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   robotmemory.ParentTable,
			Columns: []string{robotmemory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   robotmemory.ParentTable,
			Columns: []string{robotmemory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   robotmemory.ChildrenTable,
			Columns: []string{robotmemory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   robotmemory.ChildrenTable,
			Columns: []string{robotmemory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   robotmemory.ChildrenTable,
			Columns: []string{robotmemory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{robotmemory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RobotMemoryUpdateOne is the builder for updating a single RobotMemory entity.
type RobotMemoryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RobotMemoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RobotMemoryUpdateOne) SetUpdatedAt(v time.Time) *RobotMemoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRobotRef sets the "robot_ref" field.
func (_u *RobotMemoryUpdateOne) SetRobotRef(v string) *RobotMemoryUpdateOne {
	_u.mutation.SetRobotRef(v)
	return _u
}

// SetNillableRobotRef sets the "robot_ref" field if the given value is not nil.
func (_u *RobotMemoryUpdateOne) SetNillableRobotRef(v *string) *RobotMemoryUpdateOne {
	if v != nil {
		_u.SetRobotRef(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *RobotMemoryUpdateOne) SetParentID(v xid.ID) *RobotMemoryUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *RobotMemoryUpdateOne) SetNillableParentID(v *xid.ID) *RobotMemoryUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *RobotMemoryUpdateOne) ClearParentID() *RobotMemoryUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetContent sets the "content" field.
func (_u *RobotMemoryUpdateOne) SetContent(v string) *RobotMemoryUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *RobotMemoryUpdateOne) SetNillableContent(v *string) *RobotMemoryUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *RobotMemoryUpdateOne) SetSubject(v string) *RobotMemoryUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *RobotMemoryUpdateOne) SetNillableSubject(v *string) *RobotMemoryUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// ClearSubject clears the value of the "subject" field.
func (_u *RobotMemoryUpdateOne) ClearSubject() *RobotMemoryUpdateOne {
	_u.mutation.ClearSubject()
	return _u
}

// SetPredicate sets the "predicate" field.
func (_u *RobotMemoryUpdateOne) SetPredicate(v string) *RobotMemoryUpdateOne {
	_u.mutation.SetPredicate(v)
	return _u
}

// SetNillablePredicate sets the "predicate" field if the given value is not nil.
func (_u *RobotMemoryUpdateOne) SetNillablePredicate(v *string) *RobotMemoryUpdateOne {
	if v != nil {
		_u.SetPredicate(*v)
	}
	return _u
}

// ClearPredicate clears the value of the "predicate" field.
func (_u *RobotMemoryUpdateOne) ClearPredicate() *RobotMemoryUpdateOne {
	_u.mutation.ClearPredicate()
	return _u
}

// SetObject sets the "object" field.
func (_u *RobotMemoryUpdateOne) SetObject(v string) *RobotMemoryUpdateOne {
	_u.mutation.SetObject(v)
	return _u
}

// SetNillableObject sets the "object" field if the given value is not nil.
func (_u *RobotMemoryUpdateOne) SetNillableObject(v *string) *RobotMemoryUpdateOne {
	if v != nil {
		_u.SetObject(*v)
	}
	return _u
}

// ClearObject clears the value of the "object" field.
func (_u *RobotMemoryUpdateOne) ClearObject() *RobotMemoryUpdateOne {
	_u.mutation.ClearObject()
	return _u
}

// SetState sets the "state" field.
func (_u *RobotMemoryUpdateOne) SetState(v robotmemory.State) *RobotMemoryUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *RobotMemoryUpdateOne) SetNillableState(v *robotmemory.State) *RobotMemoryUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetLastAccessedAt sets the "last_accessed_at" field.
func (_u *RobotMemoryUpdateOne) SetLastAccessedAt(v time.Time) *RobotMemoryUpdateOne {
	_u.mutation.SetLastAccessedAt(v)
	return _u
}

// SetNillableLastAccessedAt sets the "last_accessed_at" field if the given value is not nil.
func (_u *RobotMemoryUpdateOne) SetNillableLastAccessedAt(v *time.Time) *RobotMemoryUpdateOne {
	if v != nil {
		_u.SetLastAccessedAt(*v)
	}
	return _u
}

// SetAccessCount sets the "access_count" field.
func (_u *RobotMemoryUpdateOne) SetAccessCount(v uint64) *RobotMemoryUpdateOne {
	_u.mutation.ResetAccessCount()
	_u.mutation.SetAccessCount(v)
	return _u
}

// SetNillableAccessCount sets the "access_count" field if the given value is not nil.
func (_u *RobotMemoryUpdateOne) SetNillableAccessCount(v *uint64) *RobotMemoryUpdateOne {
	if v != nil {
		_u.SetAccessCount(*v)
	}
	return _u
}

// AddAccessCount adds value to the "access_count" field.
func (_u *RobotMemoryUpdateOne) AddAccessCount(v int64) *RobotMemoryUpdateOne {
	_u.mutation.AddAccessCount(v)
	return _u
}

// SetParent sets the "parent" edge to the RobotMemory entity.
func (_u *RobotMemoryUpdateOne) SetParent(v *RobotMemory) *RobotMemoryUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the RobotMemory entity by IDs.
func (_u *RobotMemoryUpdateOne) AddChildIDs(ids ...xid.ID) *RobotMemoryUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the RobotMemory entity.
func (_u *RobotMemoryUpdateOne) AddChildren(v ...*RobotMemory) *RobotMemoryUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the RobotMemoryMutation object of the builder.
func (_u *RobotMemoryUpdateOne) Mutation() *RobotMemoryMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the RobotMemory entity.
func (_u *RobotMemoryUpdateOne) ClearParent() *RobotMemoryUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the RobotMemory entity.
func (_u *RobotMemoryUpdateOne) ClearChildren() *RobotMemoryUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to RobotMemory entities by IDs.
func (_u *RobotMemoryUpdateOne) RemoveChildIDs(ids ...xid.ID) *RobotMemoryUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to RobotMemory entities.
func (_u *RobotMemoryUpdateOne) RemoveChildren(v ...*RobotMemory) *RobotMemoryUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the RobotMemoryUpdate builder.
func (_u *RobotMemoryUpdateOne) Where(ps ...predicate.RobotMemory) *RobotMemoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RobotMemoryUpdateOne) Select(field string, fields ...string) *RobotMemoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RobotMemory entity.
func (_u *RobotMemoryUpdateOne) Save(ctx context.Context) (*RobotMemory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RobotMemoryUpdateOne) SaveX(ctx context.Context) *RobotMemory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RobotMemoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RobotMemoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RobotMemoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := robotmemory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RobotMemoryUpdateOne) check() error {
	if v, ok := _u.mutation.RobotRef(); ok {
		if err := robotmemory.RobotRefValidator(v); err != nil {
			return &ValidationError{Name: "robot_ref", err: fmt.Errorf(`ent: validator failed for field "RobotMemory.robot_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := robotmemory.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "RobotMemory.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := robotmemory.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "RobotMemory.state": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RobotMemoryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RobotMemoryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RobotMemoryUpdateOne) sqlSave(ctx context.Context) (_node *RobotMemory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(robotmemory.Table, robotmemory.Columns, sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RobotMemory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, robotmemory.FieldID)
		for _, f := range fields {
			if !robotmemory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != robotmemory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(robotmemory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RobotRef(); ok {
		_spec.SetField(robotmemory.FieldRobotRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(robotmemory.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(robotmemory.FieldSubject, field.TypeString, value)
	}
	if _u.mutation.SubjectCleared() {
		_spec.ClearField(robotmemory.FieldSubject, field.TypeString)
	}
	if value, ok := _u.mutation.Predicate(); ok {
		_spec.SetField(robotmemory.FieldPredicate, field.TypeString, value)
	}
	if _u.mutation.PredicateCleared() {
		_spec.ClearField(robotmemory.FieldPredicate, field.TypeString)
	}
	if value, ok := _u.mutation.Object(); ok {
		_spec.SetField(robotmemory.FieldObject, field.TypeString, value)
	}
	if _u.mutation.ObjectCleared() {
		_spec.ClearField(robotmemory.FieldObject, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(robotmemory.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastAccessedAt(); ok {
		_spec.SetField(robotmemory.FieldLastAccessedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccessCount(); ok {
		_spec.SetField(robotmemory.FieldAccessCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAccessCount(); ok {
		_spec.AddField(robotmemory.FieldAccessCount, field.TypeUint64, value)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   robotmemory.ParentTable,
			Columns: []string{robotmemory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   robotmemory.ParentTable,
			Columns: []string{robotmemory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   robotmemory.ChildrenTable,
			Columns: []string{robotmemory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   robotmemory.ChildrenTable,
			Columns: []string{robotmemory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   robotmemory.ChildrenTable,
			Columns: []string{robotmemory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(robotmemory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RobotMemory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{robotmemory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
