app          = "tagwatch-weaviate"
kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[build]
    image = "cr.weaviate.io/semitechnologies/weaviate:1.23.12"

[env]
    ASSET_STORAGE_TYPE                      = "s3"
    AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED = "true"
    CLUSTER_HOSTNAME                        = "node1"
    DEFAULT_VECTORIZER_MODULE               = "text2vec-openai"
    ENABLE_MODULES                          = 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
    PERSISTENCE_DATA_PATH                   = "/var/lib/weaviate"
    QUERY_DEFAULTS_LIMIT                    = "25"

[mounts]
    destination = "/var/lib/weaviate"
    source      = "tagwatch_weaviate_data"

[[vm]]
    cpu_kind = 'shared'
    cpus     = 1
    memory   = '1gb'
