/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
 * OpenAPI spec version: 1
 */

export interface AccountAuthMethodProps {
  /** True if the account is using this auth method. */
  active: boolean;
}
