/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
 * OpenAPI spec version: 1
 */

export interface AdminSettingsMutableProps {
  title?: string;
  description?: string;
  accent_colour?: string;
}
