/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * storyden
 * OpenAPI spec version: 1
 */

/**
 * A description of an error including a human readable message.
 */
export interface APIError {
  error: string;
  message?: string;
  suggested?: string;
  [key: string]: any;
}
