/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
 * OpenAPI spec version: 1
 */

/**
 * An asset source URL holds the address of an off-platform media asset which is not hosted on a Storyden instance. It may represent a source URL for an intended download or an asset which is stored elsewhere.
 */
export type AssetSourceURL = string;
