/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
 * OpenAPI spec version: 1
 */

/**
 * Arbitrary metadata for the resource.
 */
export interface Metadata {
  [key: string]: any;
}
