/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * storyden
 * OpenAPI spec version: 1
 */
import type { PublicProfile } from "./publicProfile";

/**
 * OK
 */
export type ProfilesGetSuccessResponse = PublicProfile;
