// Code generated by ent, DO NOT EDIT.

package robotmcpserver

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rs/xid"
)

const (
	// Label holds the string label denoting the robotmcpserver type in the database.
	Label = "robot_mcp_server"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEndpointURL holds the string denoting the endpoint_url field in the database.
	FieldEndpointURL = "endpoint_url"
	// FieldOauthRemoteConnectionID holds the string denoting the oauth_remote_connection_id field in the database.
	FieldOauthRemoteConnectionID = "oauth_remote_connection_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldBearerToken holds the string denoting the bearer_token field in the database.
	FieldBearerToken = "bearer_token"
	// FieldLastRefreshedAt holds the string denoting the last_refreshed_at field in the database.
	FieldLastRefreshedAt = "last_refreshed_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldAddedBy holds the string denoting the added_by field in the database.
	FieldAddedBy = "added_by"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeOauthRemoteConnection holds the string denoting the oauth_remote_connection edge name in mutations.
	EdgeOauthRemoteConnection = "oauth_remote_connection"
	// EdgeTools holds the string denoting the tools edge name in mutations.
	EdgeTools = "tools"
	// Table holds the table name of the robotmcpserver in the database.
	Table = "robot_mcp_servers"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "robot_mcp_servers"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "added_by"
	// OauthRemoteConnectionTable is the table that holds the oauth_remote_connection relation/edge.
	OauthRemoteConnectionTable = "robot_mcp_servers"
	// OauthRemoteConnectionInverseTable is the table name for the OAuthRemoteConnection entity.
	// It exists in this package in order to avoid circular dependency with the "oauthremoteconnection" package.
	OauthRemoteConnectionInverseTable = "oauth_remote_connections"
	// OauthRemoteConnectionColumn is the table column denoting the oauth_remote_connection relation/edge.
	OauthRemoteConnectionColumn = "oauth_remote_connection_id"
	// ToolsTable is the table that holds the tools relation/edge.
	ToolsTable = "robot_mcp_tools"
	// ToolsInverseTable is the table name for the RobotMCPTool entity.
	// It exists in this package in order to avoid circular dependency with the "robotmcptool" package.
	ToolsInverseTable = "robot_mcp_tools"
	// ToolsColumn is the table column denoting the tools relation/edge.
	ToolsColumn = "server_id"
)

// Columns holds all SQL columns for robotmcpserver fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldSlug,
	FieldDescription,
	FieldEndpointURL,
	FieldOauthRemoteConnectionID,
	FieldEnabled,
	FieldBearerToken,
	FieldLastRefreshedAt,
	FieldLastError,
	FieldAddedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// EndpointURLValidator is a validator for the "endpoint_url" field. It is called by the builders before save.
	EndpointURLValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() xid.ID
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the RobotMCPServer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByEndpointURL orders the results by the endpoint_url field.
func ByEndpointURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpointURL, opts...).ToFunc()
}

// ByOauthRemoteConnectionID orders the results by the oauth_remote_connection_id field.
func ByOauthRemoteConnectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOauthRemoteConnectionID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByBearerToken orders the results by the bearer_token field.
func ByBearerToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBearerToken, opts...).ToFunc()
}

// ByLastRefreshedAt orders the results by the last_refreshed_at field.
func ByLastRefreshedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByAddedBy orders the results by the added_by field.
func ByAddedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddedBy, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByOauthRemoteConnectionField orders the results by oauth_remote_connection field.
func ByOauthRemoteConnectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOauthRemoteConnectionStep(), sql.OrderByField(field, opts...))
	}
}

// ByToolsCount orders the results by tools count.
func ByToolsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newToolsStep(), opts...)
	}
}

// ByTools orders the results by tools terms.
func ByTools(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newToolsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
func newOauthRemoteConnectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OauthRemoteConnectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OauthRemoteConnectionTable, OauthRemoteConnectionColumn),
	)
}
func newToolsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ToolsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ToolsTable, ToolsColumn),
	)
}
