// Code generated by enumerator. DO NOT EDIT.

package email_queue

import (
	"database/sql/driver"
	"fmt"
)

type Status struct {
	v statusEnum
}

var (
	StatusPending    = Status{statusPending}
	StatusProcessing = Status{statusProcessing}
	StatusSent       = Status{statusSent}
	StatusFailed     = Status{statusFailed}
)

func (r Status) Format(f fmt.State, verb rune) {
	switch verb {
	case 's':
		fmt.Fprint(f, r.v)
	case 'q':
		fmt.Fprintf(f, "%q", r.String())
	default:
		fmt.Fprint(f, r.v)
	}
}
func (r Status) String() string {
	return string(r.v)
}
func (r Status) MarshalText() ([]byte, error) {
	return []byte(r.v), nil
}
func (r *Status) UnmarshalText(__iNpUt__ []byte) error {
	s, err := NewStatus(string(__iNpUt__))
	if err != nil {
		return err
	}
	*r = s
	return nil
}
func (r Status) Value() (driver.Value, error) {
	return r.v, nil
}
func (r *Status) Scan(__iNpUt__ any) error {
	s, err := NewStatus(fmt.Sprint(__iNpUt__))
	if err != nil {
		return err
	}
	*r = s
	return nil
}
func NewStatus(__iNpUt__ string) (Status, error) {
	switch __iNpUt__ {
	case string(statusPending):
		return StatusPending, nil
	case string(statusProcessing):
		return StatusProcessing, nil
	case string(statusSent):
		return StatusSent, nil
	case string(statusFailed):
		return StatusFailed, nil
	default:
		return Status{}, fmt.Errorf("invalid value for type 'Status': '%s'", __iNpUt__)
	}
}
