// Code generated by opencli. DO NOT EDIT.

package cligen

import (
	"context"
	"fmt"
	"github.com/spf13/cobra"
)

type ApiCollectionListOutput string

const (
	ApiCollectionListOutputJson ApiCollectionListOutput = "json"
	ApiCollectionListOutputRaw  ApiCollectionListOutput = "raw"
)

type ApiCollectionListParams struct {
	Context          string
	AccountHandle    string
	AccountHandleSet bool
	HasItem          string
	HasItemSet       bool
	Page             string
	PageSet          bool
	Output           ApiCollectionListOutput
	OutputFile       string
	Timeout          string
}
type ApiCollectionListHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ApiCollectionListParams) error

func newApiCollectionListCommand(apiCollectionList ApiCollectionListHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "list",
		Short:   "List collections using the filtering options, newest first.",
		Long:    "# List collections using the filtering options, newest first\n\nList collections using the filtering options, newest first.\n\nCollections accumulate with members, so results are paginated.\n\n\nInspect the local request and response contract with `sd api schema\nCollectionList`. This calls `GET /collections` using the selected account.\nThe server enforces permissions.\n\n## Output and automation\n\nThe default `--output json` preserves the complete server response,\nincluding nested fields and pagination metadata. Empty responses print\n`null`; HEAD responses contain `status` and `headers`. Errors go to stderr\nand return a nonzero exit status. This command fetches one page; pass\n`--page` explicitly to continue according to response pagination metadata.\n",
		Example: `  sd collection list`,
		Args:    rangeArgs(0, 0),
	}

	var rawAccountHandle string
	cmd.Flags().StringVar(&rawAccountHandle, "account-handle", "", "Account handle.")
	var rawHasItem string
	cmd.Flags().StringVar(&rawHasItem, "has-item", "", "When specified, will include a field in the response indicating whether")
	var rawPage string
	cmd.Flags().StringVar(&rawPage, "page", "", "Pagination query parameters.")
	var rawOutput string
	cmd.Flags().StringVarP(&rawOutput, "output", "o", "json", "Response format: json (default) or raw bytes. Empty JSON responses print null; HEAD prints status and headers.")
	var rawOutputFile string
	cmd.Flags().StringVar(&rawOutputFile, "output-file", "", "Write successful response bytes to this path instead of stdout; overwrites the file.")
	var rawTimeout string
	cmd.Flags().StringVar(&rawTimeout, "timeout", "60s", "Request timeout including response reads, such as 60s. Use 0s for no deadline.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		accountHandleSet := cmd.Flags().Changed("account-handle")
		hasItemSet := cmd.Flags().Changed("has-item")
		pageSet := cmd.Flags().Changed("page")
		rawContext, _ := cmd.Flags().GetString("context")
		var output ApiCollectionListOutput
		if rawOutput != "" {
			switch rawOutput {
			case "json":
				output = ApiCollectionListOutputJson
			case "raw":
				output = ApiCollectionListOutputRaw
			default:
				return fmt.Errorf("invalid --output %q: must be one of json, raw", rawOutput)
			}
		}

		p := ApiCollectionListParams{
			Context:          rawContext,
			AccountHandle:    rawAccountHandle,
			AccountHandleSet: accountHandleSet,
			HasItem:          rawHasItem,
			HasItemSet:       hasItemSet,
			Page:             rawPage,
			PageSet:          pageSet,
			Output:           output,
			OutputFile:       rawOutputFile,
			Timeout:          rawTimeout,
		}

		return apiCollectionList(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ApiCollectionCreateOutput string

const (
	ApiCollectionCreateOutputJson ApiCollectionCreateOutput = "json"
	ApiCollectionCreateOutputRaw  ApiCollectionCreateOutput = "raw"
)

type ApiCollectionCreateParams struct {
	Context     string
	Data        string
	File        string
	ContentType string
	Output      ApiCollectionCreateOutput
	OutputFile  string
	Timeout     string
}
type ApiCollectionCreateHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ApiCollectionCreateParams) error

func newApiCollectionCreateCommand(apiCollectionCreate ApiCollectionCreateHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "create",
		Short:   "Create a collection for curating posts under the authenticated account.",
		Long:    "# Create a collection for curating posts under the authenticated account\n\nCreate a collection for curating posts under the authenticated account.\n\n## Request body\n\nSend JSON using `--file payload.json`, `--file -`, or `--data`. Top-level\nfields:\n\n- `name` (string, required).\n- `slug` (string).\n- `description` (string).\n\nInspect the local request and response contract with `sd api schema\nCollectionCreate`. This calls `POST /collections` using the selected\naccount. The server enforces permissions. The request executes\nimmediately; this is not a dry run. After an uncertain network failure,\ninspect current state before retrying a mutation.\n\n## Output and automation\n\nThe default `--output json` preserves the complete server response,\nincluding nested fields and pagination metadata. Empty responses print\n`null`; HEAD responses contain `status` and `headers`. Errors go to stderr\nand return a nonzero exit status. This command sends one request; it does\nnot automatically traverse pages or cursors.\n",
		Example: `  sd collection create --file payload.json`,
		Args:    rangeArgs(0, 0),
	}

	var rawData string
	cmd.Flags().StringVar(&rawData, "data", "", "Inline request JSON. Prefer --file for large documents or secrets.")
	var rawFile string
	cmd.Flags().StringVar(&rawFile, "file", "", "Request body file; - reads stdin. Required when --data is omitted.")
	var rawContentType string
	cmd.Flags().StringVar(&rawContentType, "content-type", "", "Request media type; defaults to application/json for JSON operations, otherwise application/octet-stream.")
	var rawOutput string
	cmd.Flags().StringVarP(&rawOutput, "output", "o", "json", "Response format: json (default) or raw bytes. Empty JSON responses print null; HEAD prints status and headers.")
	var rawOutputFile string
	cmd.Flags().StringVar(&rawOutputFile, "output-file", "", "Write successful response bytes to this path instead of stdout; overwrites the file.")
	var rawTimeout string
	cmd.Flags().StringVar(&rawTimeout, "timeout", "60s", "Request timeout including response reads, such as 60s. Use 0s for no deadline.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		rawContext, _ := cmd.Flags().GetString("context")
		var output ApiCollectionCreateOutput
		if rawOutput != "" {
			switch rawOutput {
			case "json":
				output = ApiCollectionCreateOutputJson
			case "raw":
				output = ApiCollectionCreateOutputRaw
			default:
				return fmt.Errorf("invalid --output %q: must be one of json, raw", rawOutput)
			}
		}

		p := ApiCollectionCreateParams{
			Context:     rawContext,
			Data:        rawData,
			File:        rawFile,
			ContentType: rawContentType,
			Output:      output,
			OutputFile:  rawOutputFile,
			Timeout:     rawTimeout,
		}

		return apiCollectionCreate(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ApiCollectionGetOutput string

const (
	ApiCollectionGetOutputJson ApiCollectionGetOutput = "json"
	ApiCollectionGetOutputRaw  ApiCollectionGetOutput = "raw"
)

type ApiCollectionGetParams struct {
	Context        string
	Output         ApiCollectionGetOutput
	OutputFile     string
	Timeout        string
	CollectionMark string
}
type ApiCollectionGetHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ApiCollectionGetParams) error

func newApiCollectionGetCommand(apiCollectionGet ApiCollectionGetHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "get <collection-mark>",
		Short:   "Get a collection by its ID.",
		Long:    "# Get a collection by its ID\n\nRead a collection using its mark (ID or full ID-slug). The server enforces\nvisibility and ownership rules.\n\nInspect the local request and response contract with `sd api schema\nCollectionGet`. This calls `GET /collections/{collection_mark}` using the\nselected account. The server enforces permissions.\n\n## Output and automation\n\nThe default `--output json` preserves the complete server response,\nincluding nested fields and pagination metadata. Empty responses print\n`null`; HEAD responses contain `status` and `headers`. Errors go to stderr\nand return a nonzero exit status. This command sends one request; it does\nnot automatically traverse pages or cursors.\n",
		Example: `  sd collection get COLLECTION_MARK`,
		Args:    rangeArgs(1, 1),
	}

	var rawOutput string
	cmd.Flags().StringVarP(&rawOutput, "output", "o", "json", "Response format: json (default) or raw bytes. Empty JSON responses print null; HEAD prints status and headers.")
	var rawOutputFile string
	cmd.Flags().StringVar(&rawOutputFile, "output-file", "", "Write successful response bytes to this path instead of stdout; overwrites the file.")
	var rawTimeout string
	cmd.Flags().StringVar(&rawTimeout, "timeout", "60s", "Request timeout including response reads, such as 60s. Use 0s for no deadline.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		rawContext, _ := cmd.Flags().GetString("context")
		var output ApiCollectionGetOutput
		if rawOutput != "" {
			switch rawOutput {
			case "json":
				output = ApiCollectionGetOutputJson
			case "raw":
				output = ApiCollectionGetOutputRaw
			default:
				return fmt.Errorf("invalid --output %q: must be one of json, raw", rawOutput)
			}
		}
		rawCollectionMark := args[0]

		p := ApiCollectionGetParams{
			Context:        rawContext,
			Output:         output,
			OutputFile:     rawOutputFile,
			Timeout:        rawTimeout,
			CollectionMark: rawCollectionMark,
		}

		return apiCollectionGet(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ApiCollectionUpdateOutput string

const (
	ApiCollectionUpdateOutputJson ApiCollectionUpdateOutput = "json"
	ApiCollectionUpdateOutputRaw  ApiCollectionUpdateOutput = "raw"
)

type ApiCollectionUpdateParams struct {
	Context        string
	Data           string
	File           string
	ContentType    string
	Output         ApiCollectionUpdateOutput
	OutputFile     string
	Timeout        string
	CollectionMark string
}
type ApiCollectionUpdateHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ApiCollectionUpdateParams) error

func newApiCollectionUpdateCommand(apiCollectionUpdate ApiCollectionUpdateHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "update <collection-mark>",
		Short:   "Update a collection owned by the authenticated account.",
		Long:    "# Update a collection owned by the authenticated account\n\nUpdate a collection owned by the authenticated account.\n\n## Request body\n\nSend JSON using `--file payload.json`, `--file -`, or `--data`. Top-level\nfields:\n\n- `name` (string).\n- `slug` (string).\n- `description` (string).\n\nInspect the local request and response contract with `sd api schema\nCollectionUpdate`. This calls `PATCH /collections/{collection_mark}` using\nthe selected account. The server enforces permissions. The request\nexecutes immediately; this is not a dry run. After an uncertain network\nfailure, inspect current state before retrying a mutation.\n\n## Output and automation\n\nThe default `--output json` preserves the complete server response,\nincluding nested fields and pagination metadata. Empty responses print\n`null`; HEAD responses contain `status` and `headers`. Errors go to stderr\nand return a nonzero exit status. This command sends one request; it does\nnot automatically traverse pages or cursors.\n",
		Example: `  sd collection update COLLECTION_MARK --file payload.json`,
		Args:    rangeArgs(1, 1),
	}

	var rawData string
	cmd.Flags().StringVar(&rawData, "data", "", "Inline request JSON. Prefer --file for large documents or secrets.")
	var rawFile string
	cmd.Flags().StringVar(&rawFile, "file", "", "Request body file; - reads stdin. Required when --data is omitted.")
	var rawContentType string
	cmd.Flags().StringVar(&rawContentType, "content-type", "", "Request media type; defaults to application/json for JSON operations, otherwise application/octet-stream.")
	var rawOutput string
	cmd.Flags().StringVarP(&rawOutput, "output", "o", "json", "Response format: json (default) or raw bytes. Empty JSON responses print null; HEAD prints status and headers.")
	var rawOutputFile string
	cmd.Flags().StringVar(&rawOutputFile, "output-file", "", "Write successful response bytes to this path instead of stdout; overwrites the file.")
	var rawTimeout string
	cmd.Flags().StringVar(&rawTimeout, "timeout", "60s", "Request timeout including response reads, such as 60s. Use 0s for no deadline.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		rawContext, _ := cmd.Flags().GetString("context")
		var output ApiCollectionUpdateOutput
		if rawOutput != "" {
			switch rawOutput {
			case "json":
				output = ApiCollectionUpdateOutputJson
			case "raw":
				output = ApiCollectionUpdateOutputRaw
			default:
				return fmt.Errorf("invalid --output %q: must be one of json, raw", rawOutput)
			}
		}
		rawCollectionMark := args[0]

		p := ApiCollectionUpdateParams{
			Context:        rawContext,
			Data:           rawData,
			File:           rawFile,
			ContentType:    rawContentType,
			Output:         output,
			OutputFile:     rawOutputFile,
			Timeout:        rawTimeout,
			CollectionMark: rawCollectionMark,
		}

		return apiCollectionUpdate(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ApiCollectionDeleteOutput string

const (
	ApiCollectionDeleteOutputJson ApiCollectionDeleteOutput = "json"
	ApiCollectionDeleteOutputRaw  ApiCollectionDeleteOutput = "raw"
)

type ApiCollectionDeleteParams struct {
	Context        string
	Output         ApiCollectionDeleteOutput
	OutputFile     string
	Timeout        string
	CollectionMark string
}
type ApiCollectionDeleteHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ApiCollectionDeleteParams) error

func newApiCollectionDeleteCommand(apiCollectionDelete ApiCollectionDeleteHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "delete <collection-mark>",
		Short:   "Delete a collection owned by the authenticated account.",
		Long:    "# Delete a collection owned by the authenticated account\n\nDelete a collection owned by the authenticated account.\n\n\nInspect the local request and response contract with `sd api schema\nCollectionDelete`. This calls `DELETE /collections/{collection_mark}`\nusing the selected account. The server enforces permissions. The request\nexecutes immediately; this is not a dry run. After an uncertain network\nfailure, inspect current state before retrying a mutation.\n\n## Output and automation\n\nThe default `--output json` preserves the complete server response,\nincluding nested fields and pagination metadata. Empty responses print\n`null`; HEAD responses contain `status` and `headers`. Errors go to stderr\nand return a nonzero exit status. This command sends one request; it does\nnot automatically traverse pages or cursors.\n",
		Example: `  sd collection delete COLLECTION_MARK`,
		Args:    rangeArgs(1, 1),
	}

	var rawOutput string
	cmd.Flags().StringVarP(&rawOutput, "output", "o", "json", "Response format: json (default) or raw bytes. Empty JSON responses print null; HEAD prints status and headers.")
	var rawOutputFile string
	cmd.Flags().StringVar(&rawOutputFile, "output-file", "", "Write successful response bytes to this path instead of stdout; overwrites the file.")
	var rawTimeout string
	cmd.Flags().StringVar(&rawTimeout, "timeout", "60s", "Request timeout including response reads, such as 60s. Use 0s for no deadline.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		rawContext, _ := cmd.Flags().GetString("context")
		var output ApiCollectionDeleteOutput
		if rawOutput != "" {
			switch rawOutput {
			case "json":
				output = ApiCollectionDeleteOutputJson
			case "raw":
				output = ApiCollectionDeleteOutputRaw
			default:
				return fmt.Errorf("invalid --output %q: must be one of json, raw", rawOutput)
			}
		}
		rawCollectionMark := args[0]

		p := ApiCollectionDeleteParams{
			Context:        rawContext,
			Output:         output,
			OutputFile:     rawOutputFile,
			Timeout:        rawTimeout,
			CollectionMark: rawCollectionMark,
		}

		return apiCollectionDelete(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ApiCollectionAddPostOutput string

const (
	ApiCollectionAddPostOutputJson ApiCollectionAddPostOutput = "json"
	ApiCollectionAddPostOutputRaw  ApiCollectionAddPostOutput = "raw"
)

type ApiCollectionAddPostParams struct {
	Context        string
	Output         ApiCollectionAddPostOutput
	OutputFile     string
	Timeout        string
	CollectionMark string
	PostId         string
}
type ApiCollectionAddPostHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ApiCollectionAddPostParams) error

func newApiCollectionAddPostCommand(apiCollectionAddPost ApiCollectionAddPostHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "add <collection-mark> <post-id>",
		Short:   "Add a post to a collection.",
		Long:    "# Add a post to a collection\n\nAdd a post to a collection. The collection must be owned by the account\nmaking the request. The post can be any published post of any kind.\n\n\nInspect the local request and response contract with `sd api schema\nCollectionAddPost`. This calls `PUT\n/collections/{collection_mark}/posts/{post_id}` using the selected\naccount. The server enforces permissions. The request executes\nimmediately; this is not a dry run. After an uncertain network failure,\ninspect current state before retrying a mutation.\n\n## Output and automation\n\nThe default `--output json` preserves the complete server response,\nincluding nested fields and pagination metadata. Empty responses print\n`null`; HEAD responses contain `status` and `headers`. Errors go to\nstderr and return a nonzero exit status. This command sends one request;\nit does not automatically traverse pages or cursors.\n",
		Example: `  sd collection posts add COLLECTION_MARK POST_ID`,
		Args:    rangeArgs(2, 2),
	}

	var rawOutput string
	cmd.Flags().StringVarP(&rawOutput, "output", "o", "json", "Response format: json (default) or raw bytes. Empty JSON responses print null; HEAD prints status and headers.")
	var rawOutputFile string
	cmd.Flags().StringVar(&rawOutputFile, "output-file", "", "Write successful response bytes to this path instead of stdout; overwrites the file.")
	var rawTimeout string
	cmd.Flags().StringVar(&rawTimeout, "timeout", "60s", "Request timeout including response reads, such as 60s. Use 0s for no deadline.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		rawContext, _ := cmd.Flags().GetString("context")
		var output ApiCollectionAddPostOutput
		if rawOutput != "" {
			switch rawOutput {
			case "json":
				output = ApiCollectionAddPostOutputJson
			case "raw":
				output = ApiCollectionAddPostOutputRaw
			default:
				return fmt.Errorf("invalid --output %q: must be one of json, raw", rawOutput)
			}
		}
		rawCollectionMark := args[0]
		rawPostId := args[1]

		p := ApiCollectionAddPostParams{
			Context:        rawContext,
			Output:         output,
			OutputFile:     rawOutputFile,
			Timeout:        rawTimeout,
			CollectionMark: rawCollectionMark,
			PostId:         rawPostId,
		}

		return apiCollectionAddPost(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ApiCollectionRemovePostOutput string

const (
	ApiCollectionRemovePostOutputJson ApiCollectionRemovePostOutput = "json"
	ApiCollectionRemovePostOutputRaw  ApiCollectionRemovePostOutput = "raw"
)

type ApiCollectionRemovePostParams struct {
	Context        string
	Output         ApiCollectionRemovePostOutput
	OutputFile     string
	Timeout        string
	CollectionMark string
	PostId         string
}
type ApiCollectionRemovePostHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ApiCollectionRemovePostParams) error

func newApiCollectionRemovePostCommand(apiCollectionRemovePost ApiCollectionRemovePostHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "remove <collection-mark> <post-id>",
		Short:   "Remove a post from a collection.",
		Long:    "# Remove a post from a collection\n\nRemove a post from a collection. The collection must be owned by the\naccount making the request.\n\n\nInspect the local request and response contract with `sd api schema\nCollectionRemovePost`. This calls `DELETE\n/collections/{collection_mark}/posts/{post_id}` using the selected\naccount. The server enforces permissions. The request executes\nimmediately; this is not a dry run. After an uncertain network failure,\ninspect current state before retrying a mutation.\n\n## Output and automation\n\nThe default `--output json` preserves the complete server response,\nincluding nested fields and pagination metadata. Empty responses print\n`null`; HEAD responses contain `status` and `headers`. Errors go to\nstderr and return a nonzero exit status. This command sends one request;\nit does not automatically traverse pages or cursors.\n",
		Example: `  sd collection posts remove COLLECTION_MARK POST_ID`,
		Args:    rangeArgs(2, 2),
	}

	var rawOutput string
	cmd.Flags().StringVarP(&rawOutput, "output", "o", "json", "Response format: json (default) or raw bytes. Empty JSON responses print null; HEAD prints status and headers.")
	var rawOutputFile string
	cmd.Flags().StringVar(&rawOutputFile, "output-file", "", "Write successful response bytes to this path instead of stdout; overwrites the file.")
	var rawTimeout string
	cmd.Flags().StringVar(&rawTimeout, "timeout", "60s", "Request timeout including response reads, such as 60s. Use 0s for no deadline.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		rawContext, _ := cmd.Flags().GetString("context")
		var output ApiCollectionRemovePostOutput
		if rawOutput != "" {
			switch rawOutput {
			case "json":
				output = ApiCollectionRemovePostOutputJson
			case "raw":
				output = ApiCollectionRemovePostOutputRaw
			default:
				return fmt.Errorf("invalid --output %q: must be one of json, raw", rawOutput)
			}
		}
		rawCollectionMark := args[0]
		rawPostId := args[1]

		p := ApiCollectionRemovePostParams{
			Context:        rawContext,
			Output:         output,
			OutputFile:     rawOutputFile,
			Timeout:        rawTimeout,
			CollectionMark: rawCollectionMark,
			PostId:         rawPostId,
		}

		return apiCollectionRemovePost(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

func newCollectionPostsCommand(
	apiCollectionAddPost ApiCollectionAddPostHandler,
	apiCollectionRemovePost ApiCollectionRemovePostHandler,
) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "posts",
		Short: "Add posts to collections or remove their membership.",
		Long:  "# Collection Posts\n\nAdd existing posts to a collection or remove their membership. Removing\nmembership does not delete the original post.\n\nCommands send one request and return the full JSON response by default.\nUse explicit IDs from list/get output and `--context NAME` for automation.\nMutations apply immediately; check current state before retrying after a\nnetwork failure.\n\n## Examples\n\n~~~sh\nsd collection posts add --help\n~~~\n",
		Args:  groupArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}
	cmd.AddCommand(
		newApiCollectionAddPostCommand(apiCollectionAddPost),
		newApiCollectionRemovePostCommand(apiCollectionRemovePost),
	)
	return cmd
}

type ApiCollectionAddNodeOutput string

const (
	ApiCollectionAddNodeOutputJson ApiCollectionAddNodeOutput = "json"
	ApiCollectionAddNodeOutputRaw  ApiCollectionAddNodeOutput = "raw"
)

type ApiCollectionAddNodeParams struct {
	Context        string
	Output         ApiCollectionAddNodeOutput
	OutputFile     string
	Timeout        string
	CollectionMark string
	NodeId         string
}
type ApiCollectionAddNodeHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ApiCollectionAddNodeParams) error

func newApiCollectionAddNodeCommand(apiCollectionAddNode ApiCollectionAddNodeHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "add <collection-mark> <page-id>",
		Short:   "Add a page to a collection.",
		Long:    "# Add a page to a collection\n\nAdd a page to a collection. The collection must be owned by the account\nmaking the request. The page can be any published page or any page not\npublished but owned by the collection owner.\n\n\nInspect the local request and response contract with `sd api schema\nCollectionAddNode`. This calls `PUT\n/collections/{collection_mark}/nodes/{node_id}` using the selected\naccount. The server enforces permissions. The request executes\nimmediately; this is not a dry run. After an uncertain network failure,\ninspect current state before retrying a mutation.\n\n## Output and automation\n\nThe default `--output json` preserves the complete server response,\nincluding nested fields and pagination metadata. Empty responses print\n`null`; HEAD responses contain `status` and `headers`. Errors go to\nstderr and return a nonzero exit status. This command sends one request;\nit does not automatically traverse pages or cursors.\n",
		Example: `  sd collection pages add COLLECTION_MARK NODE_ID`,
		Args:    rangeArgs(2, 2),
	}

	var rawOutput string
	cmd.Flags().StringVarP(&rawOutput, "output", "o", "json", "Response format: json (default) or raw bytes. Empty JSON responses print null; HEAD prints status and headers.")
	var rawOutputFile string
	cmd.Flags().StringVar(&rawOutputFile, "output-file", "", "Write successful response bytes to this path instead of stdout; overwrites the file.")
	var rawTimeout string
	cmd.Flags().StringVar(&rawTimeout, "timeout", "60s", "Request timeout including response reads, such as 60s. Use 0s for no deadline.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		rawContext, _ := cmd.Flags().GetString("context")
		var output ApiCollectionAddNodeOutput
		if rawOutput != "" {
			switch rawOutput {
			case "json":
				output = ApiCollectionAddNodeOutputJson
			case "raw":
				output = ApiCollectionAddNodeOutputRaw
			default:
				return fmt.Errorf("invalid --output %q: must be one of json, raw", rawOutput)
			}
		}
		rawCollectionMark := args[0]
		rawNodeId := args[1]

		p := ApiCollectionAddNodeParams{
			Context:        rawContext,
			Output:         output,
			OutputFile:     rawOutputFile,
			Timeout:        rawTimeout,
			CollectionMark: rawCollectionMark,
			NodeId:         rawNodeId,
		}

		return apiCollectionAddNode(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ApiCollectionRemoveNodeOutput string

const (
	ApiCollectionRemoveNodeOutputJson ApiCollectionRemoveNodeOutput = "json"
	ApiCollectionRemoveNodeOutputRaw  ApiCollectionRemoveNodeOutput = "raw"
)

type ApiCollectionRemoveNodeParams struct {
	Context        string
	Output         ApiCollectionRemoveNodeOutput
	OutputFile     string
	Timeout        string
	CollectionMark string
	NodeId         string
}
type ApiCollectionRemoveNodeHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ApiCollectionRemoveNodeParams) error

func newApiCollectionRemoveNodeCommand(apiCollectionRemoveNode ApiCollectionRemoveNodeHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "remove <collection-mark> <page-id>",
		Short:   "Remove a page from a collection.",
		Long:    "# Remove a page from a collection\n\nRemove a page from a collection. The collection must be owned by the\naccount making the request.\n\n\nInspect the local request and response contract with `sd api schema\nCollectionRemoveNode`. This calls `DELETE\n/collections/{collection_mark}/nodes/{node_id}` using the selected\naccount. The server enforces permissions. The request executes\nimmediately; this is not a dry run. After an uncertain network failure,\ninspect current state before retrying a mutation.\n\n## Output and automation\n\nThe default `--output json` preserves the complete server response,\nincluding nested fields and pagination metadata. Empty responses print\n`null`; HEAD responses contain `status` and `headers`. Errors go to\nstderr and return a nonzero exit status. This command sends one request;\nit does not automatically traverse pages or cursors.\n",
		Example: `  sd collection pages remove COLLECTION_MARK NODE_ID`,
		Args:    rangeArgs(2, 2),
	}

	var rawOutput string
	cmd.Flags().StringVarP(&rawOutput, "output", "o", "json", "Response format: json (default) or raw bytes. Empty JSON responses print null; HEAD prints status and headers.")
	var rawOutputFile string
	cmd.Flags().StringVar(&rawOutputFile, "output-file", "", "Write successful response bytes to this path instead of stdout; overwrites the file.")
	var rawTimeout string
	cmd.Flags().StringVar(&rawTimeout, "timeout", "60s", "Request timeout including response reads, such as 60s. Use 0s for no deadline.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		rawContext, _ := cmd.Flags().GetString("context")
		var output ApiCollectionRemoveNodeOutput
		if rawOutput != "" {
			switch rawOutput {
			case "json":
				output = ApiCollectionRemoveNodeOutputJson
			case "raw":
				output = ApiCollectionRemoveNodeOutputRaw
			default:
				return fmt.Errorf("invalid --output %q: must be one of json, raw", rawOutput)
			}
		}
		rawCollectionMark := args[0]
		rawNodeId := args[1]

		p := ApiCollectionRemoveNodeParams{
			Context:        rawContext,
			Output:         output,
			OutputFile:     rawOutputFile,
			Timeout:        rawTimeout,
			CollectionMark: rawCollectionMark,
			NodeId:         rawNodeId,
		}

		return apiCollectionRemoveNode(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

func newCollectionPagesCommand(
	apiCollectionAddNode ApiCollectionAddNodeHandler,
	apiCollectionRemoveNode ApiCollectionRemoveNodeHandler,
) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "pages",
		Short: "Add Library pages to collections or remove their membership.",
		Long:  "# Collection Pages\n\nAdd existing Library pages to a collection or remove their membership.\nRemoving membership does not delete the original page.\n\nCommands send one request and return the full JSON response by default.\nUse explicit IDs from list/get output and `--context NAME` for automation.\nMutations apply immediately; check current state before retrying after a\nnetwork failure.\n\n## Examples\n\n~~~sh\nsd collection pages add --help\n~~~\n",
		Args:  groupArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}
	cmd.AddCommand(
		newApiCollectionAddNodeCommand(apiCollectionAddNode),
		newApiCollectionRemoveNodeCommand(apiCollectionRemoveNode),
	)
	return cmd
}
func NewCollectionCommand(
	apiCollectionList ApiCollectionListHandler,
	apiCollectionCreate ApiCollectionCreateHandler,
	apiCollectionGet ApiCollectionGetHandler,
	apiCollectionUpdate ApiCollectionUpdateHandler,
	apiCollectionDelete ApiCollectionDeleteHandler,
	apiCollectionAddPost ApiCollectionAddPostHandler,
	apiCollectionRemovePost ApiCollectionRemovePostHandler,
	apiCollectionAddNode ApiCollectionAddNodeHandler,
	apiCollectionRemoveNode ApiCollectionRemoveNodeHandler,
) CollectionCommand {
	cmd := &cobra.Command{
		Use:   "collection",
		Short: "Curate collections of posts and Library pages.",
		Long:  "# Collection\n\nCurate collections of posts and Library pages. Create a collection, then add\nor remove items with the posts and pages subcommands. Read the collection\nbefore editing its metadata.\n\nCommands send one request and return the full JSON response by default. Use\nexplicit IDs from list/get output and `--context NAME` for automation.\nMutations apply immediately; check current state before retrying after a\nnetwork failure.\n\n## Examples\n\n~~~sh\nsd collection list --help\n~~~\n",
		Args:  groupArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}
	cmd.AddCommand(
		newApiCollectionListCommand(apiCollectionList),
		newApiCollectionCreateCommand(apiCollectionCreate),
		newApiCollectionGetCommand(apiCollectionGet),
		newApiCollectionUpdateCommand(apiCollectionUpdate),
		newApiCollectionDeleteCommand(apiCollectionDelete),
		newCollectionPostsCommand(
			apiCollectionAddPost,
			apiCollectionRemovePost,
		),
		newCollectionPagesCommand(
			apiCollectionAddNode,
			apiCollectionRemoveNode,
		),
	)
	return CollectionCommand(cmd)
}

type CollectionCommand *cobra.Command
