/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
 * The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.
 *
 * OpenAPI spec version: v1.26.15-post
 */
import type { CollectionCommonProps } from "./collectionCommonProps";
import type { CollectionItemList } from "./collectionItemList";
import type { CommonProperties } from "./commonProperties";

/**
 * The full properties of a collection, for rendering a single collection
 * somewhere where you can afford to show all the items in the collection.
 */
export type CollectionWithItems = CommonProperties &
  CollectionCommonProps & {
    items: CollectionItemList;
  };
