/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.11-post
 */
import type { Identifier } from "./identifier";
import type { Metadata } from "./metadata";
import type { NodeName } from "./nodeName";
import type { NodeVersionContent } from "./nodeVersionContent";
import type { NodeVersionDescription } from "./nodeVersionDescription";
import type { NodeVersionReference } from "./nodeVersionReference";
import type { NodeVersionStatus } from "./nodeVersionStatus";
import type { ProfileReference } from "./profileReference";
import type { PropertyMutationList } from "./propertyMutationList";
import type { Slug } from "./slug";

/**
 * A draft or applied edit for a library node. Draft versions are mutable
working snapshots. Applied versions are immutable snapshots that were
copied into the target node upon publishing of the changes.

 */
export interface NodeVersion {
  author: ProfileReference;
  /** @nullable */
  content?: NodeVersionContent;
  created_at: string;
  /** @nullable */
  description?: NodeVersionDescription;
  id: Identifier;
  meta: Metadata;
  name: NodeName;
  node_id: Identifier;
  /** Previous applied version for historical comparison. Only present
when retrieving an individual applied version and an earlier
applied version exists.
 */
  previous?: NodeVersionReference;
  /** Complete desired-state property list for the target node.
Properties are replace-all and are not merged with existing values
when the version is applied.
 */
  properties: PropertyMutationList;
  slug: Slug;
  status: NodeVersionStatus;
  updated_at: string;
}
