/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
 * The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.
 *
 * OpenAPI spec version: v1.26.15-post
 */
import type { CreatedAt } from "./createdAt";
import type { Identifier } from "./identifier";
import type { OAuthRemoteMode } from "./oAuthRemoteMode";
import type { OAuthRemoteStatus } from "./oAuthRemoteStatus";
import type { UpdatedAt } from "./updatedAt";

export interface OAuthRemoteConnection {
  id: Identifier;
  createdAt: CreatedAt;
  updatedAt: UpdatedAt;
  resource_url: string;
  resource?: string;
  resource_name?: string;
  authorization_server?: string;
  mode: OAuthRemoteMode;
  status: OAuthRemoteStatus;
  client_id?: string;
  has_client_secret: boolean;
  authorization_endpoint?: string;
  token_endpoint?: string;
  registration_endpoint?: string;
  token_endpoint_auth_method?: string;
  redirect_uri?: string;
  redirect_uris?: string[];
  scope?: string;
  has_access_token: boolean;
  has_refresh_token: boolean;
  token_type?: string;
  token_expiry?: string;
  last_error?: string;
}
