/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.1
 */

/**
 * The body text of a post within a thread. The type is either a string or
an object, depending on what was used during creation. Strings can be
used for basic plain text or markdown content and objects are used for
more complex types such as Slate.js editor documents.

 */
export type PostContent = string;
