/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.3-canary
 */
import type { AbortPart } from "./abortPart";
import type { DataPart } from "./dataPart";
import type { ErrorPart } from "./errorPart";
import type { FilePart } from "./filePart";
import type { FinishMessagePart } from "./finishMessagePart";
import type { FinishStepPart } from "./finishStepPart";
import type { NonEmptyString } from "./nonEmptyString";
import type { ReasoningDeltaPart } from "./reasoningDeltaPart";
import type { ReasoningEndPart } from "./reasoningEndPart";
import type { ReasoningStartPart } from "./reasoningStartPart";
import type { SourceDocumentPart } from "./sourceDocumentPart";
import type { SourceUrlPart } from "./sourceUrlPart";
import type { StartPart } from "./startPart";
import type { StartStepPart } from "./startStepPart";
import type { TextDeltaPart } from "./textDeltaPart";
import type { TextEndPart } from "./textEndPart";
import type { TextStartPart } from "./textStartPart";
import type { ToolInputAvailablePart } from "./toolInputAvailablePart";
import type { ToolInputDeltaPart } from "./toolInputDeltaPart";
import type { ToolInputStartPart } from "./toolInputStartPart";
import type { ToolOutputAvailablePart } from "./toolOutputAvailablePart";

export type StreamPart =
  | (StartPart & {
      type: NonEmptyString;
    })
  | (TextStartPart & {
      type: NonEmptyString;
    })
  | (TextDeltaPart & {
      type: NonEmptyString;
    })
  | (TextEndPart & {
      type: NonEmptyString;
    })
  | (ReasoningStartPart & {
      type: NonEmptyString;
    })
  | (ReasoningDeltaPart & {
      type: NonEmptyString;
    })
  | (ReasoningEndPart & {
      type: NonEmptyString;
    })
  | (SourceUrlPart & {
      type: NonEmptyString;
    })
  | (SourceDocumentPart & {
      type: NonEmptyString;
    })
  | (FilePart & {
      type: NonEmptyString;
    })
  | (DataPart & {
      type: NonEmptyString;
    })
  | (ErrorPart & {
      type: NonEmptyString;
    })
  | (ToolInputStartPart & {
      type: NonEmptyString;
    })
  | (ToolInputDeltaPart & {
      type: NonEmptyString;
    })
  | (ToolInputAvailablePart & {
      type: NonEmptyString;
    })
  | (ToolOutputAvailablePart & {
      type: NonEmptyString;
    })
  | (StartStepPart & {
      type: NonEmptyString;
    })
  | (FinishStepPart & {
      type: NonEmptyString;
    })
  | (FinishMessagePart & {
      type: NonEmptyString;
    })
  | (AbortPart & {
      type: NonEmptyString;
    });
