name: Test frontend

on:
  push:
    branches:
      - main
    paths-ignore: &ignored_paths
      - "home/**"
      - ".vscode/**"
      - "*.md"
      - "docker/**"
      - "docker-compose.yml"
      - "fly.toml"
      - "renovate.json"
      - "*.yml"
      - "*.yaml"
      - ".nvmrc"
      - ".vercelignore"

  pull_request:
    paths-ignore: *ignored_paths

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - run: corepack enable

      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
        working-directory: web
      - run: pnpm test
        working-directory: web
