name: Test frontend

on:
  push:
    paths-ignore:
      - "home/**"
      - ".vscode/**"
      - "*.md"
      - "docker/**"
      - "docker-compose.yml"
      - "fly.toml"
      - "renovate.json"
      - "*.yml"
      - "*.yaml"
      - ".nvmrc"
      - ".vercelignore"

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
        working-directory: web
      - run: pnpm test
        working-directory: web
      - run: pnpm test:ui
        working-directory: web
